site_name: Celestia-IoT
site_description: Open-source space and environmental monitoring station
site_author: Anna Goncharova

theme: 
  name: material
  features:
    - navigation.top
    - navigation.sections
  favicon: img/favicon.ico
  icon:
    logo: material/weather-lightning
 
  palette:
    # ☀️ Дневная тема
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue    # Обязательно через дефис!
    accent: blue
    toggle:
      icon: material/weather-sunny
      name: Dark mode

    # 🌙 Космическая тема
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo   # Обязательно через дефис!
    accent: indigo     # Обязательно через дефис!
    toggle:
      icon: material/weather-night
      name: Light mode

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Data Sources: data-sources.md
  - API: api.md
  - Troubleshooting: troubleshooting.md

plugins:
  - search


